export const TOPIC_ICON_KEYS = [
  'javascript',
  'typescript',
  'html',
  'css',
  'react',
  'nextjs',
  'nodejs',
  'postgresql',
  'sql',
  'code',
  'braces',
  'file-code',
  'terminal',
  'server',
  'database',
  'globe',
  'network',
  'shield',
  'lock',
  'flask-conical',
  'bug',
  'accessibility',
  'layers',
  'boxes',
  'component',
  'cog',
  'folder',
  'book-open',
  'git-branch',
] as const;

export type TopicIconKey = (typeof TOPIC_ICON_KEYS)[number];

export const TOPIC_ICON_LABELS: Record<TopicIconKey, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  html: 'HTML',
  css: 'CSS',
  react: 'React',
  nextjs: 'Next.js',
  nodejs: 'Node.js',
  postgresql: 'PostgreSQL',
  sql: 'SQL',
  code: 'Code',
  braces: 'Braces',
  'file-code': 'File',
  terminal: 'Terminal',
  server: 'Server',
  database: 'Database',
  globe: 'Globe',
  network: 'Network',
  shield: 'Shield',
  lock: 'Lock',
  'flask-conical': 'Testing',
  bug: 'Bug',
  accessibility: 'Accessibility',
  layers: 'Layers',
  boxes: 'Boxes',
  component: 'Component',
  cog: 'Cog',
  folder: 'Folder',
  'book-open': 'Book',
  'git-branch': 'Git',
};

export function isTopicIconKey(value: string | null | undefined): value is TopicIconKey {
  return typeof value === 'string' && (TOPIC_ICON_KEYS as readonly string[]).includes(value);
}
